name: pelican-jupyter
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip

  # Dev tools
  - setuptools
  - setuptools-scm
  - pylint
  - flake8
  - black
  - isort
  - twine
  - wheel

  # Testing
  - pytest
  - pytest-cov

  # Examples
  - notebook
  - jupyterlab

  - pip:
      # Package deps
      - pelican>=4
      - nbconvert>=5,<6
      - markdown

