name: pelican-jupyter
channels:
  - conda-forge
dependencies:
  - python=3.7
  - pip

  # Base conda deps
  - setuptools
  - setuptools_scm
  - pylint
  - flake8
  - black
  - isort
  - twine
  - wheel
  - pytest
  - pytest-cov

  # This project conda deps
  - nbconvert
  - markdown
  - notebook
  - jupyterlab

  - pip:
    # This project pip deps
    - pelican
